# database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_example?useSSL=false&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: qkrtjdehd123
    password: rootpass


# jpa query
---
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        format_sql: true


# Multipart
---
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

file:
  upload-directory: C:/pilot/uploads


# Security
---
spring:
  security:
    user:
      name: user
      password: 1

#  basic:
#    enabled: false

